---
cisco_ios:
  port: 22
  connection_options:
    netmiko:
      platform: cisco_ios
      #extras:
        #session_log: netmiko_log.txt
        #secret:


# NORTH AMERICA
# These are just examples. You can have static variables based on "bigger" regions served by two
# radius servers like a country, followed by smaller regions like states/provinces that have their
# own syslog,ntp servers and so forth.

# Nornir looks up variables in a hierarchy fashion. Under hosts.yaml it will go to the first group
# and look for the variable name. If it's not found it will go to the second group and look for the
# variable etc. Priority goes from hosts.yaml --> groups.yaml --> defaults.yaml.

nam:
  data:
    ntp_server: ip of this regions ntp server
    ise_server1: ip of this regions radius server
    ise_server2: ip of this regions second radius server

region1:
  data:
    sw_server: syslog server for this region or snmp server
    ise_server1: ip of this regions radius server
    ise_server2: ip of this regions second radius server
    ip_helper1: ip of DHCP server
    ip_helper2: ip of second DHCP server
