---
cisco_ios:
  port: 22
  connection_options:
    netmiko:
      platform: cisco_ios
      #extras:
        #session_log: netmiko_log.txt
        #secret:


# NORTH AMERICA
nam:
  data:
    ntp_server: 10.19.253.80
    ise_server1: 10.70.34.55
    ise_server2: 10.60.3.1

ccv:
  data:
    sw_server: 172.17.104.203

usa:
  data:
    sw_server: 10.71.197.100

bor:
  data:
    sw_server: 10.26.0.28

mus:
  data:
    sw_server: 10.19.1.28

pen:
  data:
    sw_server: 10.80.10.23
    ise_server1: 10.80.10.11
    ise_server2: 10.70.34.55


# SOUTH AMERICA
sam:
  data:
    ntp_server: 10.120.203.30

caj:
  data:
    sw_server: 10.20.5.204
    ise_server1: 10.20.5.115
    ise_server2: 10.120.203.100

mer:
  data:
    sw_server: 10.120.163.77
    ise_server1: 10.120.203.100
    ise_server2: 10.120.203.101

cer:
  data:
    sw_server: 10.116.22.48
    ise_server1: 10.113.0.36
    ise_server2: 10.120.203.100


# AFRICA
afr:
  data:
    ntp_server: 10.222.12.222
    sw_server: 10.222.1.239
    ise_server1: 10.223.2.158
    ise_server2: 10.70.34.55


# AUSTRALIA
aus:
  data:
    ntp_server: 10.222.12.222
    sw_server: 10.96.20.170
    ise_server1: 10.96.20.139
    ise_server2: 10.70.34.55
